pizzamura_123:
  outputs:
    dev:
      dbname: dev
      host: redshift-cluster-1.chokaeute2qo.ap-southeast-1.redshift.amazonaws.com
      password: DewiPizzamura1
      port: 5439
      schema: db_pizzamura
      threads: 1
      type: redshift
      user:   
  target: dev