version: '3.8'

services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: dewi
            MYSQL_PASSWORD: dewi
        ports:
            - "3306:3306"
        volumes:
            - ./data:/var/lib/mysql
            - ./dataset/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
            - ./sql_conf/mysql.cnf:/etc/mysql/conf.d/mysqld.cnf

    adminer:
        image: adminer:latest
        restart: always
        ports:
            - 8085:8080

    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin:latest
    #     restart: always
    #     ports:
    #         - 8087:80
    #     environment:
    #         PMA_HOST: db
    #         PMA_PORT: 3306
    #         PMA_ARBITRARY: 1

networks:
  docker-network:
    external: true