# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'uc_dewi'
      MYSQL_PASSWORD: 'uc_dewi_pass'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
      - ./sql_conf:/etc/mysql/conf.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  my-db:
    